volumes:
  idm_database:
  
services:
  db:
    container_name: minidm-db
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: idm
    ports:
      - "5432:5432"
    volumes:
      - idm_database:/var/lib/postgresql
    labels:
      com.minidm.project: "minidm"
      com.minidm.service: "db"
      com.minidm.managed-by: "testcontainers"
