package identity

import (
	"context"
	"fmt"
	db "my-idm/db/sqlc"
)

type RegisterCommand struct {
	Email    string
	Password string
}

type IdentityService struct {
	q *db.Queries // Generated by sqlc
}

func NewService(q *db.Queries) *IdentityService {
	return &IdentityService{q: q}
}

func (s *IdentityService) Register(ctx context.Context, cmd RegisterCommand) (*db.Identity, error) {
	// 1. Secure Hashing
	hashed, err := HashPassword(cmd.Password)
	if err != nil {
		return nil, fmt.Errorf("hashing failed: %w", err)
	}

	// 2. Data: Call the generated SQL function
	user, err := s.q.CreateIdentity(ctx, db.CreateIdentityParams{
		SubjectID: "auth0|" + cmd.Email, // Simplified for now
		Email:     cmd.Email,
		PwHash:    string(hashed),
	})

	return &user, err
}
