// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIdentityToClientGroup = `-- name: AddIdentityToClientGroup :exec

INSERT INTO identity_client_groups (identity_id, group_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddIdentityToClientGroupParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	GroupID    pgtype.UUID `json:"group_id"`
}

// ---- Identity ↔ Group ----
func (q *Queries) AddIdentityToClientGroup(ctx context.Context, arg AddIdentityToClientGroupParams) error {
	_, err := q.db.Exec(ctx, addIdentityToClientGroup, arg.IdentityID, arg.GroupID)
	return err
}

const assignIdentityToClientRole = `-- name: AssignIdentityToClientRole :exec

INSERT INTO identity_client_roles (identity_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignIdentityToClientRoleParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	RoleID     pgtype.UUID `json:"role_id"`
}

// ---- Identity ↔ Role (direct assignment) ----
func (q *Queries) AssignIdentityToClientRole(ctx context.Context, arg AssignIdentityToClientRoleParams) error {
	_, err := q.db.Exec(ctx, assignIdentityToClientRole, arg.IdentityID, arg.RoleID)
	return err
}

const assignRoleToClientGroup = `-- name: AssignRoleToClientGroup :exec

INSERT INTO client_group_roles (group_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignRoleToClientGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

// ---- Group ↔ Role ----
func (q *Queries) AssignRoleToClientGroup(ctx context.Context, arg AssignRoleToClientGroupParams) error {
	_, err := q.db.Exec(ctx, assignRoleToClientGroup, arg.GroupID, arg.RoleID)
	return err
}

const createClientGroup = `-- name: CreateClientGroup :one

INSERT INTO oauth2_client_groups (client_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, client_id, name, description, created_at
`

type CreateClientGroupParams struct {
	ClientID    pgtype.UUID `json:"client_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// ---- Client Groups ----
func (q *Queries) CreateClientGroup(ctx context.Context, arg CreateClientGroupParams) (Oauth2ClientGroup, error) {
	row := q.db.QueryRow(ctx, createClientGroup, arg.ClientID, arg.Name, arg.Description)
	var i Oauth2ClientGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createClientRole = `-- name: CreateClientRole :one

INSERT INTO oauth2_client_roles (client_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, client_id, name, description, created_at
`

type CreateClientRoleParams struct {
	ClientID    pgtype.UUID `json:"client_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// ---- Client Roles ----
func (q *Queries) CreateClientRole(ctx context.Context, arg CreateClientRoleParams) (Oauth2ClientRole, error) {
	row := q.db.QueryRow(ctx, createClientRole, arg.ClientID, arg.Name, arg.Description)
	var i Oauth2ClientRole
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClientGroup = `-- name: DeleteClientGroup :exec
DELETE FROM oauth2_client_groups WHERE id = $1
`

func (q *Queries) DeleteClientGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClientGroup, id)
	return err
}

const deleteClientRole = `-- name: DeleteClientRole :exec
DELETE FROM oauth2_client_roles WHERE id = $1
`

func (q *Queries) DeleteClientRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClientRole, id)
	return err
}

const getClientGroup = `-- name: GetClientGroup :one
SELECT id, client_id, name, description, created_at FROM oauth2_client_groups WHERE id = $1
`

func (q *Queries) GetClientGroup(ctx context.Context, id pgtype.UUID) (Oauth2ClientGroup, error) {
	row := q.db.QueryRow(ctx, getClientGroup, id)
	var i Oauth2ClientGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getClientRole = `-- name: GetClientRole :one
SELECT id, client_id, name, description, created_at FROM oauth2_client_roles WHERE id = $1
`

func (q *Queries) GetClientRole(ctx context.Context, id pgtype.UUID) (Oauth2ClientRole, error) {
	row := q.db.QueryRow(ctx, getClientRole, id)
	var i Oauth2ClientRole
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getEffectiveClientRolesForIdentity = `-- name: GetEffectiveClientRolesForIdentity :many

SELECT DISTINCT r.name
FROM oauth2_client_roles r
WHERE r.client_id = $1::uuid
  AND r.id IN (
    SELECT role_id FROM identity_client_roles WHERE identity_id = $2::uuid
    UNION
    SELECT cgr.role_id FROM client_group_roles cgr
    JOIN identity_client_groups icg ON icg.group_id = cgr.group_id
    WHERE icg.identity_id = $2::uuid
  )
ORDER BY r.name
`

type GetEffectiveClientRolesForIdentityParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

// ---- Token issuance: effective roles ----
func (q *Queries) GetEffectiveClientRolesForIdentity(ctx context.Context, arg GetEffectiveClientRolesForIdentityParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getEffectiveClientRolesForIdentity, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientGroups = `-- name: ListClientGroups :many
SELECT id, client_id, name, description, created_at FROM oauth2_client_groups WHERE client_id = $1 ORDER BY name
`

func (q *Queries) ListClientGroups(ctx context.Context, clientID pgtype.UUID) ([]Oauth2ClientGroup, error) {
	rows, err := q.db.Query(ctx, listClientGroups, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Oauth2ClientGroup
	for rows.Next() {
		var i Oauth2ClientGroup
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientGroupsForIdentity = `-- name: ListClientGroupsForIdentity :many
SELECT g.id, g.name, g.description, g.client_id, c.name AS client_name, c.client_id AS app_client_id
FROM oauth2_client_groups g
JOIN identity_client_groups icg ON icg.group_id = g.id
JOIN oauth2_clients c ON c.id = g.client_id
WHERE icg.identity_id = $1
ORDER BY c.name, g.name
`

type ListClientGroupsForIdentityRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ClientID    pgtype.UUID `json:"client_id"`
	ClientName  string      `json:"client_name"`
	AppClientID string      `json:"app_client_id"`
}

func (q *Queries) ListClientGroupsForIdentity(ctx context.Context, identityID pgtype.UUID) ([]ListClientGroupsForIdentityRow, error) {
	rows, err := q.db.Query(ctx, listClientGroupsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientGroupsForIdentityRow
	for rows.Next() {
		var i ListClientGroupsForIdentityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.ClientName,
			&i.AppClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientRoles = `-- name: ListClientRoles :many
SELECT id, client_id, name, description, created_at FROM oauth2_client_roles WHERE client_id = $1 ORDER BY name
`

func (q *Queries) ListClientRoles(ctx context.Context, clientID pgtype.UUID) ([]Oauth2ClientRole, error) {
	rows, err := q.db.Query(ctx, listClientRoles, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Oauth2ClientRole
	for rows.Next() {
		var i Oauth2ClientRole
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectClientRolesForIdentity = `-- name: ListDirectClientRolesForIdentity :many
SELECT r.id, r.name, r.description, r.client_id, c.name AS client_name, c.client_id AS app_client_id
FROM oauth2_client_roles r
JOIN identity_client_roles icr ON icr.role_id = r.id
JOIN oauth2_clients c ON c.id = r.client_id
WHERE icr.identity_id = $1
ORDER BY c.name, r.name
`

type ListDirectClientRolesForIdentityRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ClientID    pgtype.UUID `json:"client_id"`
	ClientName  string      `json:"client_name"`
	AppClientID string      `json:"app_client_id"`
}

func (q *Queries) ListDirectClientRolesForIdentity(ctx context.Context, identityID pgtype.UUID) ([]ListDirectClientRolesForIdentityRow, error) {
	rows, err := q.db.Query(ctx, listDirectClientRolesForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectClientRolesForIdentityRow
	for rows.Next() {
		var i ListDirectClientRolesForIdentityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.ClientName,
			&i.AppClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForClientRole = `-- name: ListGroupsForClientRole :many
SELECT g.id, g.name
FROM oauth2_client_groups g
JOIN client_group_roles cgr ON cgr.group_id = g.id
WHERE cgr.role_id = $1
ORDER BY g.name
`

type ListGroupsForClientRoleRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListGroupsForClientRole(ctx context.Context, roleID pgtype.UUID) ([]ListGroupsForClientRoleRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForClientRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsForClientRoleRow
	for rows.Next() {
		var i ListGroupsForClientRoleRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesInClientGroup = `-- name: ListIdentitiesInClientGroup :many
SELECT i.id, i.email
FROM identities i
JOIN identity_client_groups icg ON icg.identity_id = i.id
WHERE icg.group_id = $1
ORDER BY i.email
`

type ListIdentitiesInClientGroupRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) ListIdentitiesInClientGroup(ctx context.Context, groupID pgtype.UUID) ([]ListIdentitiesInClientGroupRow, error) {
	rows, err := q.db.Query(ctx, listIdentitiesInClientGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentitiesInClientGroupRow
	for rows.Next() {
		var i ListIdentitiesInClientGroupRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesWithClientRole = `-- name: ListIdentitiesWithClientRole :many
SELECT i.id, i.email
FROM identities i
JOIN identity_client_roles icr ON icr.identity_id = i.id
WHERE icr.role_id = $1
ORDER BY i.email
`

type ListIdentitiesWithClientRoleRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) ListIdentitiesWithClientRole(ctx context.Context, roleID pgtype.UUID) ([]ListIdentitiesWithClientRoleRow, error) {
	rows, err := q.db.Query(ctx, listIdentitiesWithClientRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentitiesWithClientRoleRow
	for rows.Next() {
		var i ListIdentitiesWithClientRoleRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForClientGroup = `-- name: ListRolesForClientGroup :many
SELECT r.id, r.client_id, r.name, r.description, r.created_at
FROM oauth2_client_roles r
JOIN client_group_roles cgr ON cgr.role_id = r.id
WHERE cgr.group_id = $1
ORDER BY r.name
`

func (q *Queries) ListRolesForClientGroup(ctx context.Context, groupID pgtype.UUID) ([]Oauth2ClientRole, error) {
	rows, err := q.db.Query(ctx, listRolesForClientGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Oauth2ClientRole
	for rows.Next() {
		var i Oauth2ClientRole
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIdentityFromClientGroup = `-- name: RemoveIdentityFromClientGroup :exec
DELETE FROM identity_client_groups WHERE identity_id = $1 AND group_id = $2
`

type RemoveIdentityFromClientGroupParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	GroupID    pgtype.UUID `json:"group_id"`
}

func (q *Queries) RemoveIdentityFromClientGroup(ctx context.Context, arg RemoveIdentityFromClientGroupParams) error {
	_, err := q.db.Exec(ctx, removeIdentityFromClientGroup, arg.IdentityID, arg.GroupID)
	return err
}

const removeIdentityFromClientRole = `-- name: RemoveIdentityFromClientRole :exec
DELETE FROM identity_client_roles WHERE identity_id = $1 AND role_id = $2
`

type RemoveIdentityFromClientRoleParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	RoleID     pgtype.UUID `json:"role_id"`
}

func (q *Queries) RemoveIdentityFromClientRole(ctx context.Context, arg RemoveIdentityFromClientRoleParams) error {
	_, err := q.db.Exec(ctx, removeIdentityFromClientRole, arg.IdentityID, arg.RoleID)
	return err
}

const removeRoleFromClientGroup = `-- name: RemoveRoleFromClientGroup :exec
DELETE FROM client_group_roles WHERE group_id = $1 AND role_id = $2
`

type RemoveRoleFromClientGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

func (q *Queries) RemoveRoleFromClientGroup(ctx context.Context, arg RemoveRoleFromClientGroupParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromClientGroup, arg.GroupID, arg.RoleID)
	return err
}

const updateClientGroup = `-- name: UpdateClientGroup :one
UPDATE oauth2_client_groups SET name = $2, description = $3 WHERE id = $1 RETURNING id, client_id, name, description, created_at
`

type UpdateClientGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateClientGroup(ctx context.Context, arg UpdateClientGroupParams) (Oauth2ClientGroup, error) {
	row := q.db.QueryRow(ctx, updateClientGroup, arg.ID, arg.Name, arg.Description)
	var i Oauth2ClientGroup
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateClientRole = `-- name: UpdateClientRole :one
UPDATE oauth2_client_roles SET name = $2, description = $3 WHERE id = $1 RETURNING id, client_id, name, description, created_at
`

type UpdateClientRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateClientRole(ctx context.Context, arg UpdateClientRoleParams) (Oauth2ClientRole, error) {
	row := q.db.QueryRow(ctx, updateClientRole, arg.ID, arg.Name, arg.Description)
	var i Oauth2ClientRole
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
