// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIdentities = `-- name: CountIdentities :one
SELECT COUNT(*) FROM identities
`

func (q *Queries) CountIdentities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (subject_id, email, pw_hash, is_enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, subject_id, email, pw_hash, is_enabled, created_at, updated_at
`

type CreateIdentityParams struct {
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
	PwHash    string `json:"pw_hash"`
	IsEnabled bool   `json:"is_enabled"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity, arg.SubjectID, arg.Email, arg.PwHash, arg.IsEnabled)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByEmail = `-- name: GetIdentityByEmail :one
SELECT id, subject_id, email, pw_hash, is_enabled, created_at, updated_at FROM identities
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetIdentityByEmail(ctx context.Context, email string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByEmail, email)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, subject_id, email, pw_hash, is_enabled, created_at, updated_at FROM identities WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIdentityByID(ctx context.Context, id pgtype.UUID) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityBySub = `-- name: GetIdentityBySub :one
SELECT id, subject_id, email, pw_hash, is_enabled, created_at, updated_at FROM identities
WHERE subject_id = $1 LIMIT 1
`

func (q *Queries) GetIdentityBySub(ctx context.Context, subjectID string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityBySub, subjectID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, subject_id, email, pw_hash, is_enabled, created_at, updated_at FROM identities
ORDER BY created_at DESC
`

func (q *Queries) ListIdentities(ctx context.Context) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Email,
			&i.PwHash,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityEnabled = `-- name: UpdateIdentityEnabled :one
UPDATE identities SET is_enabled = $2, updated_at = NOW() WHERE id = $1
RETURNING id, subject_id, email, is_enabled, created_at, updated_at
`

type UpdateIdentityEnabledParams struct {
	ID        pgtype.UUID `json:"id"`
	IsEnabled bool        `json:"is_enabled"`
}

type UpdateIdentityEnabledRow struct {
	ID        pgtype.UUID        `json:"id"`
	SubjectID string             `json:"subject_id"`
	Email     string             `json:"email"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIdentityEnabled(ctx context.Context, arg UpdateIdentityEnabledParams) (UpdateIdentityEnabledRow, error) {
	row := q.db.QueryRow(ctx, updateIdentityEnabled, arg.ID, arg.IsEnabled)
	var i UpdateIdentityEnabledRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityPassword = `-- name: UpdateIdentityPassword :exec
UPDATE identities SET pw_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateIdentityPasswordParams struct {
	ID     pgtype.UUID `json:"id"`
	PwHash string      `json:"pw_hash"`
}

func (q *Queries) UpdateIdentityPassword(ctx context.Context, arg UpdateIdentityPasswordParams) error {
	_, err := q.db.Exec(ctx, updateIdentityPassword, arg.ID, arg.PwHash)
	return err
}
