// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package db

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (subject_id, email, pw_hash)
VALUES ($1, $2, $3)
RETURNING id, subject_id, email, pw_hash, is_enabled, created_at, updated_at
`

type CreateIdentityParams struct {
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
	PwHash    string `json:"pw_hash"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity, arg.SubjectID, arg.Email, arg.PwHash)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByEmail = `-- name: GetIdentityByEmail :one
SELECT id, subject_id, email, pw_hash, is_enabled, created_at, updated_at FROM identities
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetIdentityByEmail(ctx context.Context, email string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByEmail, email)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityBySub = `-- name: GetIdentityBySub :one
SELECT id, subject_id, email, pw_hash, is_enabled, created_at, updated_at FROM identities
WHERE subject_id = $1 LIMIT 1
`

func (q *Queries) GetIdentityBySub(ctx context.Context, subjectID string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityBySub, subjectID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Email,
		&i.PwHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
