// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Identity struct {
	ID        pgtype.UUID        `json:"id"`
	SubjectID string             `json:"subject_id"`
	Email     string             `json:"email"`
	PwHash    string             `json:"pw_hash"`
	IsEnabled bool               `json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
