// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth2.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO oauth2_authorization_codes
    (code, client_id, identity_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING code, client_id, identity_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, created_at, used, nonce
`

type CreateAuthorizationCodeParams struct {
	Code                string             `json:"code"`
	ClientID            string             `json:"client_id"`
	IdentityID          pgtype.UUID        `json:"identity_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scopes              []string           `json:"scopes"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	Nonce               pgtype.Text        `json:"nonce"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (Oauth2AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.Code,
		arg.ClientID,
		arg.IdentityID,
		arg.RedirectUri,
		arg.Scopes,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
		arg.Nonce,
	)
	var i Oauth2AuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.ClientID,
		&i.IdentityID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Used,
		&i.Nonce,
	)
	return i, err
}

const createOAuth2Client = `-- name: CreateOAuth2Client :one
INSERT INTO oauth2_clients (client_id, client_secret_hash, name, description, redirect_uris, scopes, auto_consent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_enabled, created_at, updated_at, auto_consent
`

type CreateOAuth2ClientParams struct {
	ClientID         string      `json:"client_id"`
	ClientSecretHash string      `json:"client_secret_hash"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	RedirectUris     []string    `json:"redirect_uris"`
	Scopes           []string    `json:"scopes"`
	AutoConsent      bool        `json:"auto_consent"`
}

func (q *Queries) CreateOAuth2Client(ctx context.Context, arg CreateOAuth2ClientParams) (Oauth2Client, error) {
	row := q.db.QueryRow(ctx, createOAuth2Client,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.Scopes,
		arg.AutoConsent,
	)
	var i Oauth2Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoConsent,
	)
	return i, err
}

const createOAuth2Token = `-- name: CreateOAuth2Token :one
INSERT INTO oauth2_tokens (client_id, identity_id, jti, refresh_token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, identity_id, jti, refresh_token_hash, scopes, expires_at, created_at, revoked
`

type CreateOAuth2TokenParams struct {
	ClientID         string             `json:"client_id"`
	IdentityID       pgtype.UUID        `json:"identity_id"`
	Jti              string             `json:"jti"`
	RefreshTokenHash pgtype.Text        `json:"refresh_token_hash"`
	Scopes           []string           `json:"scopes"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuth2Token(ctx context.Context, arg CreateOAuth2TokenParams) (Oauth2Token, error) {
	row := q.db.QueryRow(ctx, createOAuth2Token,
		arg.ClientID,
		arg.IdentityID,
		arg.Jti,
		arg.RefreshTokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i Oauth2Token
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.IdentityID,
		&i.Jti,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const deleteOAuth2Client = `-- name: DeleteOAuth2Client :exec
DELETE FROM oauth2_clients WHERE id = $1
`

func (q *Queries) DeleteOAuth2Client(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuth2Client, id)
	return err
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT code, client_id, identity_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, created_at, used, nonce FROM oauth2_authorization_codes
WHERE code = $1 AND used = FALSE AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetAuthorizationCode(ctx context.Context, code string) (Oauth2AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCode, code)
	var i Oauth2AuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.ClientID,
		&i.IdentityID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Used,
		&i.Nonce,
	)
	return i, err
}

const getOAuth2ClientByClientID = `-- name: GetOAuth2ClientByClientID :one
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_enabled, created_at, updated_at, auto_consent FROM oauth2_clients WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetOAuth2ClientByClientID(ctx context.Context, clientID string) (Oauth2Client, error) {
	row := q.db.QueryRow(ctx, getOAuth2ClientByClientID, clientID)
	var i Oauth2Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoConsent,
	)
	return i, err
}

const getOAuth2ClientByID = `-- name: GetOAuth2ClientByID :one
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_enabled, created_at, updated_at, auto_consent FROM oauth2_clients WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOAuth2ClientByID(ctx context.Context, id pgtype.UUID) (Oauth2Client, error) {
	row := q.db.QueryRow(ctx, getOAuth2ClientByID, id)
	var i Oauth2Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoConsent,
	)
	return i, err
}

const getOAuth2ClientPublicInfo = `-- name: GetOAuth2ClientPublicInfo :one
SELECT name, description, scopes, auto_consent FROM oauth2_clients
WHERE client_id = $1 AND is_enabled = TRUE LIMIT 1
`

type GetOAuth2ClientPublicInfoRow struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Scopes      []string    `json:"scopes"`
	AutoConsent bool        `json:"auto_consent"`
}

func (q *Queries) GetOAuth2ClientPublicInfo(ctx context.Context, clientID string) (GetOAuth2ClientPublicInfoRow, error) {
	row := q.db.QueryRow(ctx, getOAuth2ClientPublicInfo, clientID)
	var i GetOAuth2ClientPublicInfoRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Scopes,
		&i.AutoConsent,
	)
	return i, err
}

const getOAuth2TokenByJTI = `-- name: GetOAuth2TokenByJTI :one
SELECT id, client_id, identity_id, jti, refresh_token_hash, scopes, expires_at, created_at, revoked FROM oauth2_tokens
WHERE jti = $1 AND revoked = FALSE
LIMIT 1
`

func (q *Queries) GetOAuth2TokenByJTI(ctx context.Context, jti string) (Oauth2Token, error) {
	row := q.db.QueryRow(ctx, getOAuth2TokenByJTI, jti)
	var i Oauth2Token
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.IdentityID,
		&i.Jti,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const getOAuth2TokenByJTIAny = `-- name: GetOAuth2TokenByJTIAny :one
SELECT id, client_id, identity_id, jti, refresh_token_hash, scopes, expires_at, created_at, revoked FROM oauth2_tokens WHERE jti = $1 LIMIT 1
`

func (q *Queries) GetOAuth2TokenByJTIAny(ctx context.Context, jti string) (Oauth2Token, error) {
	row := q.db.QueryRow(ctx, getOAuth2TokenByJTIAny, jti)
	var i Oauth2Token
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.IdentityID,
		&i.Jti,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const getOAuth2TokenByRefreshHash = `-- name: GetOAuth2TokenByRefreshHash :one
SELECT id, client_id, identity_id, jti, refresh_token_hash, scopes, expires_at, created_at, revoked FROM oauth2_tokens
WHERE refresh_token_hash = $1 AND revoked = FALSE AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetOAuth2TokenByRefreshHash(ctx context.Context, refreshTokenHash pgtype.Text) (Oauth2Token, error) {
	row := q.db.QueryRow(ctx, getOAuth2TokenByRefreshHash, refreshTokenHash)
	var i Oauth2Token
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.IdentityID,
		&i.Jti,
		&i.RefreshTokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const listActiveOAuth2Tokens = `-- name: ListActiveOAuth2Tokens :many
SELECT
    t.id,
    t.client_id,
    t.identity_id,
    t.jti,
    t.scopes,
    t.expires_at,
    t.created_at,
    i.email AS identity_email
FROM oauth2_tokens t
JOIN identities i ON i.id = t.identity_id
WHERE t.revoked = FALSE AND t.expires_at > NOW()
ORDER BY t.created_at DESC
`

type ListActiveOAuth2TokensRow struct {
	ID            pgtype.UUID        `json:"id"`
	ClientID      string             `json:"client_id"`
	IdentityID    pgtype.UUID        `json:"identity_id"`
	Jti           string             `json:"jti"`
	Scopes        []string           `json:"scopes"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	IdentityEmail string             `json:"identity_email"`
}

func (q *Queries) ListActiveOAuth2Tokens(ctx context.Context) ([]ListActiveOAuth2TokensRow, error) {
	rows, err := q.db.Query(ctx, listActiveOAuth2Tokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOAuth2TokensRow
	for rows.Next() {
		var i ListActiveOAuth2TokensRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.IdentityID,
			&i.Jti,
			&i.Scopes,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.IdentityEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuth2Clients = `-- name: ListOAuth2Clients :many
SELECT id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_enabled, created_at, updated_at, auto_consent FROM oauth2_clients ORDER BY created_at DESC
`

func (q *Queries) ListOAuth2Clients(ctx context.Context) ([]Oauth2Client, error) {
	rows, err := q.db.Query(ctx, listOAuth2Clients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Oauth2Client
	for rows.Next() {
		var i Oauth2Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.Name,
			&i.Description,
			&i.RedirectUris,
			&i.Scopes,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoConsent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthorizationCodeUsed = `-- name: MarkAuthorizationCodeUsed :exec
UPDATE oauth2_authorization_codes SET used = TRUE WHERE code = $1
`

func (q *Queries) MarkAuthorizationCodeUsed(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, markAuthorizationCodeUsed, code)
	return err
}

const revokeOAuth2Token = `-- name: RevokeOAuth2Token :exec
UPDATE oauth2_tokens SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeOAuth2Token(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuth2Token, id)
	return err
}

const updateOAuth2Client = `-- name: UpdateOAuth2Client :one
UPDATE oauth2_clients
SET name = $2, description = $3, redirect_uris = $4, scopes = $5, is_enabled = $6, auto_consent = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, client_secret_hash, name, description, redirect_uris, scopes, is_enabled, created_at, updated_at, auto_consent
`

type UpdateOAuth2ClientParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	RedirectUris []string    `json:"redirect_uris"`
	Scopes       []string    `json:"scopes"`
	IsEnabled    bool        `json:"is_enabled"`
	AutoConsent  bool        `json:"auto_consent"`
}

func (q *Queries) UpdateOAuth2Client(ctx context.Context, arg UpdateOAuth2ClientParams) (Oauth2Client, error) {
	row := q.db.QueryRow(ctx, updateOAuth2Client,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.Scopes,
		arg.IsEnabled,
		arg.AutoConsent,
	)
	var i Oauth2Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.Description,
		&i.RedirectUris,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoConsent,
	)
	return i, err
}

const updateOAuth2ClientSecret = `-- name: UpdateOAuth2ClientSecret :exec
UPDATE oauth2_clients SET client_secret_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateOAuth2ClientSecretParams struct {
	ID               pgtype.UUID `json:"id"`
	ClientSecretHash string      `json:"client_secret_hash"`
}

func (q *Queries) UpdateOAuth2ClientSecret(ctx context.Context, arg UpdateOAuth2ClientSecretParams) error {
	_, err := q.db.Exec(ctx, updateOAuth2ClientSecret, arg.ID, arg.ClientSecretHash)
	return err
}
