// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToIdentity = `-- name: AssignRoleToIdentity :exec
INSERT INTO identity_roles (identity_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToIdentityParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	RoleID     pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToIdentity(ctx context.Context, arg AssignRoleToIdentityParams) error {
	_, err := q.db.Exec(ctx, assignRoleToIdentity, arg.IdentityID, arg.RoleID)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at, updated_at FROM roles WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityHasPermission = `-- name: IdentityHasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM identity_roles ir
    JOIN permissions p   ON p.role_id     = ir.role_id
    JOIN resources   res ON res.id         = p.resource_id
    JOIN actions     a   ON a.id           = p.action_id
    WHERE ir.identity_id = $1
      AND res.name       = $2
      AND a.name         = $3
) AS has_permission
`

type IdentityHasPermissionParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Name       string      `json:"name"`
	Name_2     string      `json:"name_2"`
}

func (q *Queries) IdentityHasPermission(ctx context.Context, arg IdentityHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, identityHasPermission, arg.IdentityID, arg.Name, arg.Name_2)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listPermissionsForIdentity = `-- name: ListPermissionsForIdentity :many
SELECT DISTINCT res.name AS resource, a.name AS action
FROM identity_roles ir
JOIN permissions p   ON p.role_id     = ir.role_id
JOIN resources   res ON res.id         = p.resource_id
JOIN actions     a   ON a.id           = p.action_id
WHERE ir.identity_id = $1
ORDER BY res.name, a.name
`

type ListPermissionsForIdentityRow struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) ListPermissionsForIdentity(ctx context.Context, identityID pgtype.UUID) ([]ListPermissionsForIdentityRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsForIdentityRow
	for rows.Next() {
		var i ListPermissionsForIdentityRow
		if err := rows.Scan(&i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at, updated_at FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForIdentity = `-- name: ListRolesForIdentity :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at
FROM roles r
JOIN identity_roles ir ON ir.role_id = r.id
WHERE ir.identity_id = $1
ORDER BY r.name
`

func (q *Queries) ListRolesForIdentity(ctx context.Context, identityID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromIdentity = `-- name: RemoveRoleFromIdentity :exec
DELETE FROM identity_roles
WHERE identity_id = $1 AND role_id = $2
`

type RemoveRoleFromIdentityParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	RoleID     pgtype.UUID `json:"role_id"`
}

func (q *Queries) RemoveRoleFromIdentity(ctx context.Context, arg RemoveRoleFromIdentityParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromIdentity, arg.IdentityID, arg.RoleID)
	return err
}
