// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, identity_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, identity_id, expires_at, created_at
`

type CreateSessionParams struct {
	TokenHash  string             `json:"token_hash"`
	IdentityID pgtype.UUID        `json:"identity_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.IdentityID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.IdentityID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsByIdentityID = `-- name: DeleteSessionsByIdentityID :exec
DELETE FROM sessions WHERE identity_id = $1
`

func (q *Queries) DeleteSessionsByIdentityID(ctx context.Context, identityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByIdentityID, identityID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT token_hash, identity_id, expires_at, created_at FROM sessions
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.IdentityID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSessionsByIdentityID = `-- name: ListActiveSessionsByIdentityID :many
SELECT token_hash, identity_id, expires_at, created_at FROM sessions
WHERE identity_id = $1 AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsByIdentityID(ctx context.Context, identityID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByIdentityID, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.IdentityID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
